name: Django CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.9', '3.10']
        redis-version: ['6']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        cache-dependency-path: poetry.lock
    - name: Install poetry
      shell: bash
      run: |
          python -m pip --quiet install poetry
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH
    - name: Install dependencies
      run: poetry install
    - name: Start Redis
      uses: supercharge/redis-github-action@1.4.0
      with:
        redis-version: ${{ matrix.redis-version }}
    - name: Run Tests
      run: |
        cd testproject19
        poetry run coverage run manage.py test scheduler
    - name: Coverage report
      id: coverage_report
      uses: mathiasvr/command-output@v1
      with:
        run: |
          mv testproject19/.coverage .
          poetry run coverage report
    - uses: mshick/add-pr-comment@v1
      with:
        message: |
          Coverage report python ${{ matrix.python-version }} (python 3.9 tests with django 3.2, while 3.10 tests with latest):
          ```
          ${{ steps.coverage_report.outputs.stdout }}
          ```
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        repo-token-user-login: 'github-actions[bot]'
        allow-repeats: true
